owner: Auction-Bot
repo: status

sites:
  - name: Docs
    url: https://auction-bot.github.io/docs/
    icon: https://raw.githubusercontent.com/Auction-Bot/docs/master/Homepage/wwwroot/favicon.svg

status-website:
  theme: night
  baseUrl: /status
  faviconSvg: https://raw.githubusercontent.com/Auction-Bot/docs/master/Homepage/wwwroot/favicon.svg
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Auction Bot
  introTitle: "**Auction Bot** uptime monitoring and status page"
  introMessage: Interruptions to Auction Bot services will be posted here.
  navbar:
    - title: Home
      href: https://auction-bot.github.io/docs
    - title: Status
      href: /status
    - title: GitHub
      href: https://github.com/Auction-Bot/status
