owner: Auction-Bot
repo: status

sites:
  - name: Docs
    url: https://auction-bot.github.io/docs/
    icon: https://raw.githubusercontent.com/Auction-Bot/docs/master/Homepage/wwwroot/favicon.svg
  - name: Bot Instance [shard:1]
    url: $API_SHARD_ENDPOINT/0
    __dangerous__insecure: true
    __dangerous__body_degraded: '"status":"Connecting"'
    __dangerous__body_down: '"status":"Offline"'
  - name: Bot Instance [shard:2]
    url: $API_SHARD_ENDPOINT/1
    __dangerous__insecure: true
    __dangerous__body_degraded: '"status":"Connecting"'
    __dangerous__body_down: '"status":"Offline"'    
  - name: Bot Instance [shard:3]
    url: $API_SHARD_ENDPOINT/2
    __dangerous__insecure: true
    __dangerous__body_degraded: '"status":"Connecting"'
    __dangerous__body_down: '"status":"Offline"'    
  - name: Bot Instance [shard:4]
    url: $API_SHARD_ENDPOINT/3
    __dangerous__insecure: true
    __dangerous__body_degraded: '"status":"Connecting"'
    __dangerous__body_down: '"status":"Offline"'   
status-website:
  theme: night
  baseUrl: /status
  faviconSvg: https://raw.githubusercontent.com/Auction-Bot/docs/master/Homepage/wwwroot/favicon.svg
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Auction Bot
  introTitle: "**Auction Bot** uptime monitoring and status page"
  introMessage: Interruptions to Auction Bot services will be posted here.
  metaTags:
    - name: "author"
      content: "Anu6is"  
    - name: "description"
      content: "View the status of Auction Bot services (Website & Bot)"
    - name: "keywords"
      content: "Auction Bot, Status, Uptime, Downtime, Up, Down, Online, Offline"  
    - name: "og:type"
      content: "website"
    - name: "og:url"
      content: "https://status.auctionbot.xyz/"
    - name: "og:title"
      content: "Auction Bot - Status"
    - name: "og:description"
      content: "Service acvitity monitor and status page."
    - name: "og:image"
      content: "https://cdn.discordapp.com/attachments/392788567622942730/1145464518059769866/image.png"  
  navbar:
    - title: Home
      href: https://auction-bot.github.io/docs
    - title: Status
      href: /status
    - title: GitHub
      href: https://github.com/Auction-Bot/status
